name: Next.js CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  kiem-tra-code:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Lấy code về
        uses: actions/checkout@v4

      - name: 2. Cài Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 3. Cài thư viện
        run: npm ci

      - name: 4. Kiểm tra lỗi (Lint)
        run: npm run lint

      - name: 5. Build thử
        run: npm run build